### ISSUE TITLE
Use OpenAI for parsing and selecting events with FreeStuff

### ISSUE THREAD

**Issue by danagutu** [danagutu/FreeFind#4]
### Problem
FreeFind only parses the Bristol SU website. With the current code, we need to adapt it again for each new events website.

### Solution
Use OpenAI to parse the HTML of events websites and select the events with FreeStuff.

### Task
- [ ] Find more events websites for the University of Bristol and the city of Bristol
- [ ] Engineer a reliable prompt that works for most events websites' HTML
- [ ] Select all the events with FreeStuff and include them in the Firebase database

**Comment by danagutu** [comment]
(edit - moved comment to description)

**Comment by carolus4** [comment]
here are some thoughts:

1. there are risks with the OpenAI parser. We've already seen it hallucinate
2. there is an unknown cost/benefit. Which websites are we crawling next? What information do we want? How hard is it to add a website right now, vs building a new kind of parser?
3. is there a cost implication if you try and do some operations frequently? For example to check for cancelled events

On the other hand - I think this is very cool! For example, you don't have to worry about BristolSU changing the website. 
And the cost is minimal.

I would recomment you use this approach to build the _next_ parser, rather than try to apply back to BSU.
cf:
- #3
