### ISSUE TITLE
Create an updates system

### ISSUE THREAD

**Issue by danagutu** [danagutu/FreeFind#6]
## Problem
People want to stay updated with the events.

## Solution
Send emails with updates.

## Task
- [ ] Learn about password hashing, HTTPS, authentication tools, unique identifiers
- [ ] Set up a user database
- [ ] Choose an ESP
- [ ] Create an (un)subscribe mechanism

**Comment by danagutu** [comment]
(moved to description)

**Comment by carolus4** [comment]
I _strongly_ recommend using Firebase or at least OAuth - and never worrying about password hashing!

Or check out AuthZero if you don't like the firebase approach
