### ISSUE TITLE
Crawl events daily

### ISSUE THREAD

**Issue by carolus4** [danagutu/FreeFind#7]
### Problem
People want to only see events coming up, and also see all events coming up

### Solution
Running crawlers as a daily process 

### Tasks / Approach
- [ ] Learn about cron jobs
- [ ] Learn about running a server (optional scope)
- [ ] Get all new events
- [ ] Update events to remove cancelled, or past events
